# Generated by Django 4.1.6 on 2023-04-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=200)),
                ('runtime', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=250)),
                ('genres', models.CharField(max_length=200)),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
